### ISSUE TITLE
Como lo uso 

### ISSUE THREAD

**Issue by Luk8a** [Apollo-Burton/War_Thunder_Assist#1]
Hola no sé dónde se descarga muchas gracias

**Comment by Apollo-Burton** [comment]
Hola, no hablo español por lo que estoy usando el traductor de Google. Me disculpo si esto es confuso.

Este programa aún no está completamente listo. Funciona correctamente cuando solo hay aviones detrás de ti, pero cuando también hay tanques, el programa no reproducirá la alerta.

Si desea usarlo, hay muchos pasos complicados para ejecutarlo en su computadora.

Todas las instrucciones están en el archivo "instructions.txt" en la página de inicio.

déjame saber si tienes alguna otra pregunta.

**Comment by Apollo-Burton** [comment]
> Hola no sé dónde se descarga muchas gracias

Hola, no hablo español por lo que estoy usando el traductor de Google. Me disculpo si esto es confuso.

Este programa aún no está completamente listo. Funciona correctamente cuando solo hay aviones detrás de ti, pero cuando también hay tanques, el programa no reproducirá la alerta.

Si desea usarlo, hay muchos pasos complicados para ejecutarlo en su computadora.

Todas las instrucciones están en el archivo "instructions.txt" en la página de inicio.

déjame saber si tienes alguna otra pregunta.
